{
 "title": "Relay",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "WC Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Messages / 1 minute",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(relay_websocket_messages_total[1m])"
    }
   ]
  },
  {
   "title": "Active WS Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "relay_websocket_new_connections-relay_websocket_closed_connections"
    },
    { "expr": "relay_process_open_fds" }
   ]
  },
  {
   "title": "Node Event Loop Lag Seconds",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "relay_nodejs_eventloop_lag_seconds"
    }
   ]
  },
  {
   "title": "Connections/min",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(relay_websocket_new_connections[1m])",
     "legendFormat": "New Connections"
    },
    {
     "expr": "rate(relay_websocket_closed_connections[1m])",
     "legendFormat": "Closed Connections"
    }
   ]
  },
  {
   "title": "Ratio Closed/New Connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(relay_websocket_closed_connections[5m])/rate(relay_websocket_new_connections[5m])"
    }
   ]
  },
  {
   "title": "NodeJS Default Prometheus Metrics ",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 }
  },
  {
   "title": "Event Loop Lag Mean Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "relay_nodejs_eventloop_lag_mean_seconds"
    }
   ]
  },
  {
   "title": "CPU Seconds",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(relay_process_cpu_seconds_total[1m])",
     "legendFormat": "CPU Seconds Total"
    },
    {
     "expr": "rate(relay_process_cpu_system_seconds_total[1m])",
     "legendFormat": "CPU System Seconds Total"
    },
    {
     "expr": "rate(relay_process_cpu_user_seconds_total[1m])",
     "legendFormat": "CPU User Seconds Total"
    }
   ]
  }
 ]
}