FROM node:16.14-alpine as base

WORKDIR /monorepo

RUN apk --update --no-cache \
    add g++ make python3

FROM base as build

WORKDIR /monorepo

COPY ./ ./
RUN npm ci
RUN npm run bootstrap -- --ci
RUN npm run build

CMD ["node", "-v"]

